# Use the prepared data of the prepare_csv_data notebook to verify that our features are great to use for phishing detection

In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


### the events_augmented.csv is generated by the prepare_csv_data notebook

In [14]:
#load the prepared data
events = pd.read_csv("events_augmented.csv")
events.head()


Unnamed: 0  index      id        date  attribute_count  Tag  \
0           0  19625  287833  2022-04-01               28    0   
1           1  19626  287834  2022-04-01               79    0   
2           2  19627  287835  2022-04-01               89    1   
3           3  19628  287836  2022-04-01              159    1   
4           4  19629  287837  2022-04-01               62    0   

                                              header  \
0  Delivered-To: UNDISCLOSEDFORPRIVACY@PRIVACYDOM...   
1  Delivered-To: UNDISCLOSEDFORPRIVACY@PRIVACYDOM...   
2  Received: from 10.194.205.88\r\n by atlas109.s...   
3  Received: from 10.213.249.35\r\n by atlas106.s...   
4  Received: from 10.194.205.88\r\n by atlas103.s...   

                                                from  \
0  earleenlpwoodman2593@gmail.com|earleenlpwoodma...   
1  quickbooks@notification.intuit.com|quickbooks@...   
2    fortune@msg.fortune.com|fortune@msg.fortune.com   
3  miltongrovesc.yahoo.com@send.mailchimpapp.com|...   
4  pedidos@riooffsite.com.br|pedidos@riooffsite.c...   

                                       feedback_time  \
0  2022-03-31T23:21:12.000000+0000|2022-03-31T23:...   
1  2022-04-01T00:26:28.000000+0000|2022-04-01T00:...   
2  2022-04-01T00:58:47.000000+0000|2022-04-01T00:...   
3  2022-04-01T00:55:55.000000+0000|2022-04-01T00:...   
4  2022-04-01T00:56:38.000000+0000|2022-04-01T00:...   

                                                host  from_count  host_count  \
0                          www1.nyc.gov|www1.nyc.gov           2           2   
1  links.notification.intuit.com|links.notificati...           2          12   
2  fortune.com|fortune.com|fortune.com|fortune.co...           2          16   
3  mailchi.mp|miltongrovesc.us15.list-manage.com|...           2          30   
4  u10225017.ct.sendgrid.net|usaa.com|u10225017.c...           2          10   

   host_count_ln                                            subject  
0       0.693147                        Welcome to Your Survey-6668  
1       2.484907               Invoice 30148805 from Norton Billing  
2       2.772589  CBD - The Hottest Thing In 2022 - New Year New...  
3       3.401197                                    Happy Dietday!   
4       2.302585               Verify mobile number on your profile

In [15]:
events["numbers_in_subject"] = ''

def count_numbers(row):
    return sum(c.isdigit() for c in str(row["subject"]))

events["numbers_in_subject"] = events.apply(lambda row: count_numbers(row), axis=1)

events.head()

Unnamed: 0  index      id        date  attribute_count  Tag  \
0           0  19625  287833  2022-04-01               28    0   
1           1  19626  287834  2022-04-01               79    0   
2           2  19627  287835  2022-04-01               89    1   
3           3  19628  287836  2022-04-01              159    1   
4           4  19629  287837  2022-04-01               62    0   

                                              header  \
0  Delivered-To: UNDISCLOSEDFORPRIVACY@PRIVACYDOM...   
1  Delivered-To: UNDISCLOSEDFORPRIVACY@PRIVACYDOM...   
2  Received: from 10.194.205.88\r\n by atlas109.s...   
3  Received: from 10.213.249.35\r\n by atlas106.s...   
4  Received: from 10.194.205.88\r\n by atlas103.s...   

                                                from  \
0  earleenlpwoodman2593@gmail.com|earleenlpwoodma...   
1  quickbooks@notification.intuit.com|quickbooks@...   
2    fortune@msg.fortune.com|fortune@msg.fortune.com   
3  miltongrovesc.yahoo.com@send.mailchimpapp.com|...   
4  pedidos@riooffsite.com.br|pedidos@riooffsite.c...   

                                       feedback_time  \
0  2022-03-31T23:21:12.000000+0000|2022-03-31T23:...   
1  2022-04-01T00:26:28.000000+0000|2022-04-01T00:...   
2  2022-04-01T00:58:47.000000+0000|2022-04-01T00:...   
3  2022-04-01T00:55:55.000000+0000|2022-04-01T00:...   
4  2022-04-01T00:56:38.000000+0000|2022-04-01T00:...   

                                                host  from_count  host_count  \
0                          www1.nyc.gov|www1.nyc.gov           2           2   
1  links.notification.intuit.com|links.notificati...           2          12   
2  fortune.com|fortune.com|fortune.com|fortune.co...           2          16   
3  mailchi.mp|miltongrovesc.us15.list-manage.com|...           2          30   
4  u10225017.ct.sendgrid.net|usaa.com|u10225017.c...           2          10   

   host_count_ln                                            subject  \
0       0.693147                        Welcome to Your Survey-6668   
1       2.484907               Invoice 30148805 from Norton Billing   
2       2.772589  CBD - The Hottest Thing In 2022 - New Year New...   
3       3.401197                                    Happy Dietday!    
4       2.302585               Verify mobile number on your profile   

   numbers_in_subject  
0                   4  
1                   8  
2                   4  
3                   0  
4                   0

In [16]:
events["subject_size"] = ''

def subject_size(row):
    return len(str(row["subject"]))

events["subject_size"] = events.apply(lambda row: subject_size(row), axis=1)

events.head()

Unnamed: 0  index      id        date  attribute_count  Tag  \
0           0  19625  287833  2022-04-01               28    0   
1           1  19626  287834  2022-04-01               79    0   
2           2  19627  287835  2022-04-01               89    1   
3           3  19628  287836  2022-04-01              159    1   
4           4  19629  287837  2022-04-01               62    0   

                                              header  \
0  Delivered-To: UNDISCLOSEDFORPRIVACY@PRIVACYDOM...   
1  Delivered-To: UNDISCLOSEDFORPRIVACY@PRIVACYDOM...   
2  Received: from 10.194.205.88\r\n by atlas109.s...   
3  Received: from 10.213.249.35\r\n by atlas106.s...   
4  Received: from 10.194.205.88\r\n by atlas103.s...   

                                                from  \
0  earleenlpwoodman2593@gmail.com|earleenlpwoodma...   
1  quickbooks@notification.intuit.com|quickbooks@...   
2    fortune@msg.fortune.com|fortune@msg.fortune.com   
3  miltongrovesc.yahoo.com@send.mailchimpapp.com|...   
4  pedidos@riooffsite.com.br|pedidos@riooffsite.c...   

                                       feedback_time  \
0  2022-03-31T23:21:12.000000+0000|2022-03-31T23:...   
1  2022-04-01T00:26:28.000000+0000|2022-04-01T00:...   
2  2022-04-01T00:58:47.000000+0000|2022-04-01T00:...   
3  2022-04-01T00:55:55.000000+0000|2022-04-01T00:...   
4  2022-04-01T00:56:38.000000+0000|2022-04-01T00:...   

                                                host  from_count  host_count  \
0                          www1.nyc.gov|www1.nyc.gov           2           2   
1  links.notification.intuit.com|links.notificati...           2          12   
2  fortune.com|fortune.com|fortune.com|fortune.co...           2          16   
3  mailchi.mp|miltongrovesc.us15.list-manage.com|...           2          30   
4  u10225017.ct.sendgrid.net|usaa.com|u10225017.c...           2          10   

   host_count_ln                                            subject  \
0       0.693147                        Welcome to Your Survey-6668   
1       2.484907               Invoice 30148805 from Norton Billing   
2       2.772589  CBD - The Hottest Thing In 2022 - New Year New...   
3       3.401197                                    Happy Dietday!    
4       2.302585               Verify mobile number on your profile   

   numbers_in_subject  subject_size  
0                   4            27  
1                   8            36  
2                   4            68  
3                   0            15  
4                   0            36

In [17]:
events["subject_special_chars"] = ''

def count_special_chars(row):
    return sum((not c.isdigit() and not c.isalpha() and not c.isspace()) for c in str(row["subject"]))

events["subject_special_chars"] = events.apply(lambda row: count_special_chars(row), axis=1)

events.head()

Unnamed: 0  index      id        date  attribute_count  Tag  \
0           0  19625  287833  2022-04-01               28    0   
1           1  19626  287834  2022-04-01               79    0   
2           2  19627  287835  2022-04-01               89    1   
3           3  19628  287836  2022-04-01              159    1   
4           4  19629  287837  2022-04-01               62    0   

                                              header  \
0  Delivered-To: UNDISCLOSEDFORPRIVACY@PRIVACYDOM...   
1  Delivered-To: UNDISCLOSEDFORPRIVACY@PRIVACYDOM...   
2  Received: from 10.194.205.88\r\n by atlas109.s...   
3  Received: from 10.213.249.35\r\n by atlas106.s...   
4  Received: from 10.194.205.88\r\n by atlas103.s...   

                                                from  \
0  earleenlpwoodman2593@gmail.com|earleenlpwoodma...   
1  quickbooks@notification.intuit.com|quickbooks@...   
2    fortune@msg.fortune.com|fortune@msg.fortune.com   
3  miltongrovesc.yahoo.com@send.mailchimpapp.com|...   
4  pedidos@riooffsite.com.br|pedidos@riooffsite.c...   

                                       feedback_time  \
0  2022-03-31T23:21:12.000000+0000|2022-03-31T23:...   
1  2022-04-01T00:26:28.000000+0000|2022-04-01T00:...   
2  2022-04-01T00:58:47.000000+0000|2022-04-01T00:...   
3  2022-04-01T00:55:55.000000+0000|2022-04-01T00:...   
4  2022-04-01T00:56:38.000000+0000|2022-04-01T00:...   

                                                host  from_count  host_count  \
0                          www1.nyc.gov|www1.nyc.gov           2           2   
1  links.notification.intuit.com|links.notificati...           2          12   
2  fortune.com|fortune.com|fortune.com|fortune.co...           2          16   
3  mailchi.mp|miltongrovesc.us15.list-manage.com|...           2          30   
4  u10225017.ct.sendgrid.net|usaa.com|u10225017.c...           2          10   

   host_count_ln                                            subject  \
0       0.693147                        Welcome to Your Survey-6668   
1       2.484907               Invoice 30148805 from Norton Billing   
2       2.772589  CBD - The Hottest Thing In 2022 - New Year New...   
3       3.401197                                    Happy Dietday!    
4       2.302585               Verify mobile number on your profile   

   numbers_in_subject  subject_size  subject_special_chars  
0                   4            27                      1  
1                   8            36                      0  
2                   4            68                      3  
3                   0            15                      1  
4                   0            36                      0

## We use the data that were the more significative in the unsupervised learning notebook

In [18]:
#separate features and prediction
X, y = events[["numbers_in_subject", "subject_size", "subject_special_chars"]], events["Tag"]
print(X.shape)
print(y.shape)

(39323, 3)
(39323,)


In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=33)
print (X_train.shape, y_train.shape)

(29492, 3) (29492,)


In [20]:
#create linear classification model

from sklearn.linear_model import SGDClassifier
clf = SGDClassifier()
clf.fit(X_train, y_train)

SGDClassifier()

In [21]:
#evaluate on training set
from sklearn import metrics
y_train_pred = clf.predict(X_train)
print (metrics.accuracy_score(y_train, y_train_pred))

0.7357588498575885


In [22]:
#evaluate on test set
#Measure accuracy on the testing set
y_pred = clf.predict(X_test)
print (metrics.accuracy_score(y_test, y_pred))

0.7394975078832265


In [23]:
#support vector machine classifier
from sklearn import svm
SVM_clf = svm.SVC().fit(X_train, y_train)
SVM_prediction = SVM_clf.predict(X_test)
SVM_accuracy=100*accuracy_score(y_test, SVM_prediction)
print('','Classification Report',classification_report(y_test, SVM_prediction),'',sep='\n'+(55*'=')+'\n')
print('',"Confusion Matrix: ", confusion_matrix(y_test, SVM_prediction),'',sep='\n'+(20*'-')+'\n')
print('',f"Accuracy: {SVM_accuracy}",'',sep='\n'+(50*'*')+'\n')


Classification Report
              precision    recall  f1-score   support

           0       0.77      1.00      0.87      7540
           1       0.00      0.00      0.00      2291

    accuracy                           0.77      9831
   macro avg       0.38      0.50      0.43      9831
weighted avg       0.59      0.77      0.67      9831



--------------------
Confusion Matrix: 
--------------------
[[7540    0]
 [2291    0]]
--------------------


**************************************************
Accuracy: 76.69616519174042
**************************************************



c:\users\samuel\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\samuel\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\samuel\pycharmprojects\pythonproject\venv\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m

In [24]:
from sklearn import neighbors
knn_clf = neighbors.KNeighborsClassifier(n_neighbors=1)
knn_clf.fit(X_train,y_train)
knn_prediction = knn_clf.predict(X_test)
knn_accuracy=100*accuracy_score(y_test, knn_prediction)
print('','Classification Report',classification_report(y_test, knn_prediction),'',sep='\n'+(55*'=')+'\n')
print('',"Confusion Matrix: ", confusion_matrix(y_test, knn_prediction),'',sep='\n'+(20*'-')+'\n')
print('',f"Accuracy: {knn_accuracy}",'',sep='\n'+(50*'*')+'\n')


Classification Report
              precision    recall  f1-score   support

           0       0.80      0.87      0.83      7540
           1       0.38      0.27      0.32      2291

    accuracy                           0.73      9831
   macro avg       0.59      0.57      0.57      9831
weighted avg       0.70      0.73      0.71      9831



--------------------
Confusion Matrix: 
--------------------
[[6552  988]
 [1677  614]]
--------------------


**************************************************
Accuracy: 72.89187264774692
**************************************************



In [25]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(X_train,y_train)
LR_prediction = LR.predict(X_test)
LR_accuracy=100*accuracy_score(y_test, LR_prediction)
print('','Classification Report',classification_report(y_test, LR_prediction),'',sep='\n'+(55*'=')+'\n')
print('',"Confusion Matrix: ", confusion_matrix(y_test, LR_prediction),'',sep='\n'+(20*'-')+'\n')
print('',f"Accuracy: {LR_accuracy}",'',sep='\n'+(50*'*')+'\n')


Classification Report
              precision    recall  f1-score   support

           0       0.77      1.00      0.87      7540
           1       0.00      0.00      0.00      2291

    accuracy                           0.77      9831
   macro avg       0.38      0.50      0.43      9831
weighted avg       0.59      0.77      0.67      9831



--------------------
Confusion Matrix: 
--------------------
[[7539    1]
 [2291    0]]
--------------------


**************************************************
Accuracy: 76.68599328654257
**************************************************



In [26]:
from sklearn import tree
DT = tree.DecisionTreeClassifier()
DT.fit(X_train, y_train)
DT_prediction = DT.predict(X_test)
DT_accuracy=100.0 * accuracy_score(y_test, DT_prediction)
print('','Classification Report',classification_report(y_test, DT_prediction),'',sep='\n'+(55*'=')+'\n')
print('',"Confusion Matrix: ", confusion_matrix(y_test, DT_prediction),'',sep='\n'+(20*'-')+'\n')
print('',f"Accuracy: {DT_accuracy}",'',sep='\n'+(50*'*')+'\n')


Classification Report
              precision    recall  f1-score   support

           0       0.79      0.93      0.86      7540
           1       0.48      0.20      0.28      2291

    accuracy                           0.76      9831
   macro avg       0.64      0.57      0.57      9831
weighted avg       0.72      0.76      0.72      9831



--------------------
Confusion Matrix: 
--------------------
[[7032  508]
 [1826  465]]
--------------------


**************************************************
Accuracy: 76.25877326823314
**************************************************



## Conclusion 

Our models are unfortunately quite bad at predicting a phishing case, the accuracy is probably this high because there are more non phishing mails