In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [16]:
events = pd.read_csv("events_augmented.csv")
events.head()


Unnamed: 0  index      id        date  attribute_count  Tag  \
0           0  19625  287833  2022-04-01               28    0   
1           1  19626  287834  2022-04-01               79    0   
2           2  19627  287835  2022-04-01               89    1   
3           3  19628  287836  2022-04-01              159    1   
4           4  19629  287837  2022-04-01               62    0   

                                              header  \
0  Delivered-To: UNDISCLOSEDFORPRIVACY@PRIVACYDOM...   
1  Delivered-To: UNDISCLOSEDFORPRIVACY@PRIVACYDOM...   
2  Received: from 10.194.205.88\r\n by atlas109.s...   
3  Received: from 10.213.249.35\r\n by atlas106.s...   
4  Received: from 10.194.205.88\r\n by atlas103.s...   

                                                from  \
0  earleenlpwoodman2593@gmail.com|earleenlpwoodma...   
1  quickbooks@notification.intuit.com|quickbooks@...   
2    fortune@msg.fortune.com|fortune@msg.fortune.com   
3  miltongrovesc.yahoo.com@send.mailchimpapp.com|...   
4  pedidos@riooffsite.com.br|pedidos@riooffsite.c...   

                                       feedback_time  \
0  2022-03-31T23:21:12.000000+0000|2022-03-31T23:...   
1  2022-04-01T00:26:28.000000+0000|2022-04-01T00:...   
2  2022-04-01T00:58:47.000000+0000|2022-04-01T00:...   
3  2022-04-01T00:55:55.000000+0000|2022-04-01T00:...   
4  2022-04-01T00:56:38.000000+0000|2022-04-01T00:...   

                                                host  from_count  host_count  \
0                          www1.nyc.gov|www1.nyc.gov           2           2   
1  links.notification.intuit.com|links.notificati...           2          12   
2  fortune.com|fortune.com|fortune.com|fortune.co...           2          16   
3  mailchi.mp|miltongrovesc.us15.list-manage.com|...           2          30   
4  u10225017.ct.sendgrid.net|usaa.com|u10225017.c...           2          10   

   host_count_ln  
0       0.693147  
1       2.484907  
2       2.772589  
3       3.401197  
4       2.302585

In [17]:
#separate features and prediction
X, y = events[["host_count"]], events["Tag"]
print(X.shape)
print(y.shape)

(39323, 1)
(39323,)


In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=33)
print (X_train.shape, y_train.shape)

(29492, 1) (29492,)


In [19]:
#create linear classification model

from sklearn.linear_model import SGDClassifier
clf = SGDClassifier()
clf.fit(X_train, y_train)

SGDClassifier()

In [20]:
#evaluate on training set
from sklearn import metrics
y_train_pred = clf.predict(X_train)
print (metrics.accuracy_score(y_train, y_train_pred))

0.7167028346670283


In [21]:
#evaluate on test set
#Measure accuracy on the testing set
y_pred = clf.predict(X_test)
print (metrics.accuracy_score(y_test, y_pred))

0.7279015359576849


In [22]:
#support vector machine classifier
from sklearn import svm
SVM_clf = svm.SVC().fit(X_train, y_train)
SVM_prediction = SVM_clf.predict(X_test)
SVM_accuracy=100*accuracy_score(y_test, SVM_prediction)
print('','Classification Report',classification_report(y_test, SVM_prediction),'',sep='\n'+(55*'=')+'\n')
print('',"Confusion Matrix: ", confusion_matrix(y_test, SVM_prediction),'',sep='\n'+(20*'-')+'\n')
print('',f"Accuracy: {SVM_accuracy}",'',sep='\n'+(50*'*')+'\n')


Classification Report
              precision    recall  f1-score   support

           0       0.77      0.99      0.87      7540
           1       0.64      0.04      0.08      2291

    accuracy                           0.77      9831
   macro avg       0.71      0.52      0.47      9831
weighted avg       0.74      0.77      0.69      9831



--------------------
Confusion Matrix: 
--------------------
[[7486   54]
 [2194   97]]
--------------------


**************************************************
Accuracy: 77.13355711524768
**************************************************



In [23]:
from sklearn import neighbors
knn_clf = neighbors.KNeighborsClassifier(n_neighbors=1)
knn_clf.fit(X_train,y_train)
knn_prediction = knn_clf.predict(X_test)
knn_accuracy=100*accuracy_score(y_test, knn_prediction)
print('','Classification Report',classification_report(y_test, knn_prediction),'',sep='\n'+(55*'=')+'\n')
print('',"Confusion Matrix: ", confusion_matrix(y_test, knn_prediction),'',sep='\n'+(20*'-')+'\n')
print('',f"Accuracy: {knn_accuracy}",'',sep='\n'+(50*'*')+'\n')


Classification Report
              precision    recall  f1-score   support

           0       0.78      0.89      0.83      7540
           1       0.32      0.18      0.23      2291

    accuracy                           0.72      9831
   macro avg       0.55      0.53      0.53      9831
weighted avg       0.67      0.72      0.69      9831



--------------------
Confusion Matrix: 
--------------------
[[6676  864]
 [1887  404]]
--------------------


**************************************************
Accuracy: 72.01708880073238
**************************************************



In [24]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(X_train,y_train)
LR_prediction = LR.predict(X_test)
LR_accuracy=100*accuracy_score(y_test, LR_prediction)
print('','Classification Report',classification_report(y_test, LR_prediction),'',sep='\n'+(55*'=')+'\n')
print('',"Confusion Matrix: ", confusion_matrix(y_test, LR_prediction),'',sep='\n'+(20*'-')+'\n')
print('',f"Accuracy: {LR_accuracy}",'',sep='\n'+(50*'*')+'\n')


Classification Report
              precision    recall  f1-score   support

           0       0.77      1.00      0.87      7540
           1       0.17      0.00      0.00      2291

    accuracy                           0.77      9831
   macro avg       0.47      0.50      0.43      9831
weighted avg       0.63      0.77      0.67      9831



--------------------
Confusion Matrix: 
--------------------
[[7530   10]
 [2289    2]]
--------------------


**************************************************
Accuracy: 76.61478995015767
**************************************************



In [25]:
from sklearn import tree
DT = tree.DecisionTreeClassifier()
DT.fit(X_train, y_train)
DT_prediction = DT.predict(X_test)
DT_accuracy=100.0 * accuracy_score(y_test, DT_prediction)
print('','Classification Report',classification_report(y_test, DT_prediction),'',sep='\n'+(55*'=')+'\n')
print('',"Confusion Matrix: ", confusion_matrix(y_test, DT_prediction),'',sep='\n'+(20*'-')+'\n')
print('',f"Accuracy: {DT_accuracy}",'',sep='\n'+(50*'*')+'\n')


Classification Report
              precision    recall  f1-score   support

           0       0.77      0.99      0.87      7540
           1       0.74      0.05      0.09      2291

    accuracy                           0.77      9831
   macro avg       0.76      0.52      0.48      9831
weighted avg       0.77      0.77      0.69      9831



--------------------
Confusion Matrix: 
--------------------
[[7502   38]
 [2182  109]]
--------------------


**************************************************
Accuracy: 77.4183704607873
**************************************************



In [26]:
from sklearn.naive_bayes import GaussianNB
GB_clf=GaussianNB()
GB_clf.fit(X_train,y_train)
GB_prediction=GB_clf.predict(X_test)
GB_accuracy=100.0 * accuracy_score(y_test, GB_prediction)
print('','Classification Report',classification_report(y_test, GB_prediction),'',sep='\n'+(55*'=')+'\n')
print('',"Confusion Matrix: ", confusion_matrix(y_test, GB_prediction),'',sep='\n'+(20*'-')+'\n')
print('',f"Accuracy: {GB_accuracy}",'',sep='\n'+(50*'*')+'\n')


Classification Report
              precision    recall  f1-score   support

           0       0.77      0.97      0.86      7540
           1       0.41      0.06      0.11      2291

    accuracy                           0.76      9831
   macro avg       0.59      0.52      0.49      9831
weighted avg       0.69      0.76      0.69      9831



--------------------
Confusion Matrix: 
--------------------
[[7324  216]
 [2143  148]]
--------------------


**************************************************
Accuracy: 76.00447563828705
**************************************************

